### ISSUE TITLE
Cannot load jimp or sharp adapter with Yarn pnp

### ISSUE THREAD

**Issue by FallingSnow** [dazuaz/responsive-loader#114]
```js
$ yarn start
/project/.pnp.js:14768
    throw firstError;
    ^

Error: responsive-loader tried to access sharp, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: sharp (via "sharp")
Required by: responsive-loader@virtual:2b0c2dc8ffdb30eb93f54657423a37c414c2d30492dc0773ff771c3e2f43434196c3fec6d5f8bf8438b00007ea7c58d9754d1aa7180a72d6ef82eb9999a4c708#npm:2.0.2 (via /project/.yarn/$$virtual/responsive-loader-virtual-09d95599b5/0/cache/responsive-loader-npm-2.0.2-a84436f5c1-1c872fe215.zip/node_modules/responsive-loader/lib/adapters/)

Require stack:
- /project/.yarn/$$virtual/responsive-loader-virtual-09d95599b5/0/cache/responsive-loader-npm-2.0.2-a84436f5c1-1c872fe215.zip/node_modules/responsive-loader/lib/adapters/sharp.js
- /project/.yarn/$$virtual/responsive-loader-virtual-09d95599b5/0/cache/responsive-loader-npm-2.0.2-a84436f5c1-1c872fe215.zip/node_modules/responsive-loader/sharp.js
- /project/web/webpack.config.js
- /project/.yarn/$$virtual/webpack-cli-virtual-8dddb69c71/0/cache/webpack-cli-npm-3.3.12-3f0b130bc7-8a195df0eb.zip/node_modules/webpack-cli/bin/utils/convert-argv.js
- /project/.yarn/$$virtual/webpack-dev-server-virtual-6ef271024d/0/cache/webpack-dev-server-npm-3.11.0-42b1303dbc-1d34457456.zip/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at internalTools_makeError (/project/.pnp.js:14513:34)
    at resolveToUnqualified (/project/.pnp.js:15446:21)
    at resolveRequest (/project/.pnp.js:15532:29)
    at Object.resolveRequest (/project/.pnp.js:15598:26)
    at Function.external_module_.Module._resolveFilename (/project/.pnp.js:14745:34)
    at Function.external_module_.Module._load (/project/.pnp.js:14609:48)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/project/.yarn/$$virtual/responsive-loader-virtual-09d95599b5/0/cache/responsive-loader-npm-2.0.2-a84436f5c1-1c872fe215.zip/node_modules/responsive-loader/lib/adapters/sharp.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1200:
```

**Comment by dazuaz** [comment]
@FallingSnow Hey, thanks for reporting!

A temporary solution is to add this to ```.yarnrc.yml```
```
packageExtensions:
  "responsive-loader@*":
    dependencies:
      "sharp": "*"
```
Looks like adding ```sharp``` and ```jimp``` as ```optionalDependencies``` for ```responsive-loader``` could fix the problem, but I am having some trouble testing local changes with pnp, will leave issue open to try and sort it out.

(Sources [here](https://github.com/styled-components/styled-components/issues/3082), and [here](https://github.com/pocka/storybook-addon-designs/issues/41))

**Comment by FallingSnow** [comment]
I tried doing this but I'm not sure it works with yarn workspaces, at least the way I would expect.

I had to add the code you have above to my `.yarnrc.yml` then install `sharp` at the root directory level for it to finally work.
